service: screenshot-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1

functions:
  capture:
    handler: handler.capture # refers to function capture in handler.js
    events:
      - http: # trigger function via http request
          path: capture
          method: get
    memorySize: 1536 # RAM size for the function
    timeout: 15
    layers: # reference to the already existing layer with Chrome
      - arn:aws:lambda:us-west-1:764866452798:layer:chrome-aws-lambda:33